kind: Service
apiVersion: v1
metadata:
  name: flatris-service
spec:
  selector:
    app: flatris
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: flatris-app
    labels:
      app: flatris
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: flatris
    template:
      metadata:
        name: flatris
        labels:
          app: flatris
      spec:
        containers:
          - name: flatris-app
            image: vishal.azurecr.io/pingvishal/flatris:74
            ports:
              - containerPort: 3000
        imagePullSecrets:
          - name: acr-auth
